# this can be further extended to have different secret stores for different existingSecrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.peerdb.catalog.existingSecret }}-ext
spec:
  refreshInterval: {{ .Values.secretsStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretsStore.name }}
    kind: {{ .Values.secretsStore.kind }}
  target:
    name: {{ .Values.peerdb.catalog.existingSecret }}
    template:
      engineVersion: v2
      data:
        host: '{{`{{ .CATALOG_HOST }}`}}'
        port: '{{`{{ .CATALOG_PORT }}`}}'
        user: '{{`{{ .CATALOG_USER }}`}}'
        password: '{{`{{ .CATALOG_PASSWORD }}`}}'
        dbname: '{{`{{ .CATALOG_DATABASE }}`}}'
        uri: "postgres://{{`{{ .CATALOG_USER }}`}}:{{`{{ .CATALOG_PASSWORD }}`}}@{{`{{ .CATALOG_HOST }}`}}:{{`{{ .CATALOG_PORT }}`}}/{{`{{ .CATALOG_DATABASE }}`}}"
  data:
    - secretKey: CATALOG_HOST
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.peerdb.catalog.existingSecret }}
        property: catalog.host
    - secretKey: CATALOG_PORT
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.peerdb.catalog.existingSecret }}
        property: catalog.port
    - secretKey: CATALOG_USER
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.peerdb.catalog.existingSecret }}
        property: catalog.user
    - secretKey: CATALOG_PASSWORD
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.peerdb.catalog.existingSecret }}
        property: catalog.password
    - secretKey: CATALOG_DATABASE
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.peerdb.catalog.existingSecret }}
        property: catalog.database
