# this can be further extended to have different secret stores for different existingSecrets
{{ $secretName := (index (.Values.peerdb) "temporal-deploy").server.config.persistence.default.sql.existingSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}-ext
spec:
  refreshInterval: {{ .Values.secretsStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretsStore.name }}
    kind: {{ .Values.secretsStore.kind }}
  target:
    name: {{ .Values.peerdb.catalog.existingSecret }}
    template:
      engineVersion: v2
      data:
        password: '{{`{{ .TEMPORAL_PASSWORD }}`}}'
  data:
    - secretKey: TEMPORAL_PASSWORD
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ $secretName }}
        property: temporal.password
