# this can be further extended to have different secret stores for different existingSecrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.catalog.credentials.default.existingSecret }}-ext
spec:
  refreshInterval: {{ .Values.secretsStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretsStore.name }}
    kind: {{ .Values.secretsStore.kind }}
  target:
    name: {{ .Values.catalog.credentials.default.existingSecret }}
    template:
      engineVersion: v2
      data:
        {{- if .Values.catalog.credentials.default.existingSecretEnabledFields.user}}
        user: '{{`{{ .CATALOG_USER }}`}}'
        {{- end }}
        password: '{{`{{ .CATALOG_PASSWORD }}`}}'
  data:
    {{- if .Values.catalog.credentials.default.existingSecretEnabledFields.user}}
    - secretKey: CATALOG_USER
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.catalog.credentials.default.existingSecret }}
        property: catalog.user
    {{- end }}
    - secretKey: CATALOG_PASSWORD
      remoteRef:
        key: {{ .Values.secretsStore.keyPrefix }}/{{ .Values.catalog.credentials.default.existingSecret }}
        property: catalog.password
