{{- if .Values.authentication.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authentication.secret.name" . }}
  labels:
    {{- include "authentication.labels" . | nindent 4 }}
stringData:
  htpasswd: |
{{ include "authentication.secret.data" . | nindent 4 }}
{{- end -}}
