{{- if .Values.authentication.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authentication.config.name" . }}
  labels:
    {{- include "authentication.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ include "authentication.config.data" . | nindent 4 }}
{{- end -}}
