{{- if and (not .Values.catalog.deploy.enabled) (not .Values.catalog.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.secretName" . }}
  labels:
    {{- include "peerdb.common.labels" . | nindent 4 }}
stringData:
  host: {{ .Values.catalog.pgHost | quote }}
  port: {{ .Values.catalog.pgPort | quote }}
  user: {{ .Values.catalog.pgUser | quote }}
  password: {{ .Values.catalog.pgPassword | quote }}
  dbname:  {{ .Values.catalog.pgDatabase | quote }}
  uri: "postgres://{{ .Values.catalog.pgUser }}:{{ .Values.catalog.pgPassword }}@{{ .Values.catalog.pgHost }}:{{ .Values.catalog.pgPort }}/{{ .Values.catalog.pgDatabase }}"
{{- end }}