{{- if .Values.flowSnapshotWorker.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: flow-snapshot-service
  labels:
    {{- include "component.labels" "flow-snapshot-worker" | nindent 4 }}
    {{- include "peerdb.common.labels" . | nindent 4 }}
  annotations:
    {{- .Values.flowSnapshotWorker.service.annotations | toYaml | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "component.labels" "flow-snapshot-worker" | nindent 4 }}
    {{- include "peerdb.common.selectorLabels" . | nindent 4 }}
{{- end -}}