{{- if not (and .Values.peerdbUI.credentials.passwordExistingSecret .Values.peerdb.credentials.passwordExistingSecret .Values.peerdbUI.credentials.nexauthExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: peerdb-server-ui-secret
  labels:
    {{- include "peerdb.common.labels" . | nindent 4 }}
stringData:
  {{- if not .Values.peerdbUI.credentials.passwordExistingSecret }}
  UI_PEERDB_PASSWORD: '{{ .Values.peerdbUI.credentials.password }}'
  {{- end }}
  {{- if not .Values.peerdb.credentials.passwordExistingSecret }}
  SERVER_PEERDB_PASSWORD: '{{ .Values.peerdb.credentials.password }}'
  {{- end }}
  {{- if not .Values.peerdbUI.credentials.nexauthExistingSecret }}
  UI_NEXTAUTH_SECRET: '{{ .Values.peerdbUI.credentials.nexauth_secret | default (randAlphaNum 60) }}'
  {{- end }}
{{- end }}