{{- if .Values.peerdbUI.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerdb-ui
  labels:
    {{- include "component.labels" "peerdb-ui" | nindent 4 }}
    {{- include "peerdb.common.labels" . | nindent 4 }}
    {{- with .Values.peerdbUI.deployment.labels }}
    {{ . | toYaml | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.peerdbUI.deployment.annotations }}
    {{ . | toYaml | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.peerdbUI.replicaCount }}
  selector:
    matchLabels:
      {{- include "component.labels" "peerdb-ui" | nindent 6 }}
      {{- include "peerdb.common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "component.labels" "peerdb-ui" | nindent 8 }}
        {{- include "peerdb.common.labels" . | nindent 8 }}
        {{- with .Values.peerdbUI.pods.labels }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.peerdbUI.pods.annotations }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      terminationGracePeriodSeconds: {{ default 60 .Values.peerdbUI.terminationGracePeriodSeconds }}
      {{- include "pods.affinity" (list $ "peerdbUI") | nindent 6 }}
      {{- include "pods.nodeSelector" (list $ "peerdbUI") | nindent 6 }}
      {{- include "pods.tolerations" (list $ "peerdbUI") | nindent 6 }}
      {{- include "pods.imagePullSecrets" (list $ "peerdbUI") | nindent 6 }}

      containers:
      - name: peerdb-ui
        image: "{{ .Values.peerdbUI.image.repository }}:{{ .Values.peerdbUI.version | default .Values.peerdb.version }}"
        imagePullPolicy: {{ .Values.peerdbUI.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.peerdbUI.service.targetPort }}
          name: web
        env:
        {{- include "catalog.pgConf" . | nindent 8 }}
        # flow server config
        - name: PEERDB_FLOW_SERVER_HTTP
          value: "http://flow-api:{{ .Values.flowApi.service.httpPort }}"
        - name: PEERDB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: UI_PEERDB_PASSWORD
              name: peerdb-server-ui-secret
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              key: UI_NEXTAUTH_SECRET
              name: peerdb-server-ui-secret
        - name: NEXTAUTH_URL
          value: {{ .Values.peerdbUI.service.url }}
        {{- with .Values.peerdbUI.extraEnv -}}
        {{ . | toYaml | nindent 8}}
        {{- end }}
        livenessProbe:
          tcpSocket:
            port: web
          initialDelaySeconds: 10
          periodSeconds: 3
          failureThreshold: 3
          terminationGracePeriodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: web
          initialDelaySeconds: 10
          periodSeconds: 3
          failureThreshold: 3

        {{- with .Values.peerdbUI.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
{{- end -}}