apiVersion: v1
kind: Secret
metadata:
  name: peerdb-server-ui-secret
  labels:
    {{- include "peerdb.common.labels" . | nindent 4 }}
stringData:
  UI_PEERDB_PASSWORD: '{{ .Values.peerdbUI.credentials.password }}'
  SERVER_PEERDB_PASSWORD: '{{ .Values.peerdb.credentials.password }}'
  UI_NEXTAUTH_SECRET: '{{ .Values.peerdbUI.credentials.nexauth_secret | default (randAlphaNum 60) }}'
