{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    {{- if .Values.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.roleArn }}
    {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- include "peerdb.common.labels" . | nindent 4 }}
{{- end -}}