{{- if and .Values.credentials.ssl.enabled (not .Values.credentials.ssl.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog.ssl.certificate.defaultSecretName" . }}
  annotations:
    {{- if or .Values.schema.setup.hook.enabled .Values.schema.update.hook.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    {{- end }}
stringData:
  certificate: |
    {{- if eq .Values.credentials.ssl.type "RDS" }}
    {{- .Files.Get "aws-ca-bundle.pem" | nindent 4 }}
    {{- else }}
    {{- .Files.Get .Values.credentials.ssl.path | nindent 4 }}
    {{- end }}
{{- end }}