{{- if .Values.global.peerdb.enterprise.saveCustomerValuesAsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: values-customer-peerdb-catalog
stringData:
  "peerdb.values.customer.yaml" : |
{{ .Files.Get "values.customer.yaml" | indent 4 }}
{{- end }}