name: Release Helm Charts on Tag Push
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  actions: write
  contents: write

jobs:
  release-charts:
    runs-on: ubuntu-latest
    concurrency:
      group: release-helm-tag-push
    strategy:
      matrix:
        chartName: [peerdb, peerdb-catalog]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Call release-charts.yml
        run: |
          gh workflow run release-charts.yml \
            --ref ${{ github.ref }} \
            -f chartName=${{ matrix.chartName }} \
        env:
          GH_TOKEN: ${{ github.token }}
